#!/usr/bin/env python3

import sys
import pprint
from ruamel.yaml import YAML

yaml=YAML(typ='rt', pure=True)

events = []
for event in yaml.parse(sys.stdin.read()):
    events.append(event)

yaml.emit(events, stream=sys.stdout)
