#!/usr/bin/env python3

import sys
import pprint
import ruamel.yaml

events = []
for event in ruamel.yaml.parse(sys.stdin.read()):
    events.append(event)

output = ruamel.yaml.emit(events)
sys.stdout.write(output)
