#!/usr/bin/env python3

import sys
import pprint
from ruamel.yaml import YAML
import json

yaml = YAML(typ='safe', pure=True)

def generic_constructor(loader, tag, node):
    classname = node.__class__.__name__
    if (classname == 'SequenceNode'):
        return loader.construct_sequence(node)
    elif (classname == 'MappingNode'):
        return loader.construct_mapping(node)
    else:
        return loader.construct_scalar(node)

yaml.constructor.add_multi_constructor('', generic_constructor)

for doc in yaml.load_all(sys.stdin.read()):
    try:
        print(json.dumps(doc, sort_keys=True, skipkeys=True, indent=2))
    except:
        print("Error json.dumps:", sys.exc_info()[0])
        raise
